### ISSUE TITLE
mutiline 

### ISSUE THREAD

**Issue by dverdugo85** [raginmari/RAGTextField#7]
any idea how to do multine regards!!

**Comment by raginmari** [comment]
`RAGTextField` is a text field. Text fields on iOS do not support multiline text (`RAGTextField` is a subclass of `UITextField`). Please use `UITextView` instead.

Feel free to try and extend this class to support multiline text but I guess that may stray a little too far from the original `UITextField` so that an extension of `UITextView` should be more successful.
